### ISSUE TITLE
Remove dependence on "resource" module?

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [DennisMitchell/dodos#1]
This module (`resource`) seems to be a linux-only module and is not portable. The offending line is [dodos.py#L5](https://github.com/DennisMitchell/dodos/blob/master/dodos.py#L5). Here is the error on a windows machine:

```
λ dodos.py -B examples/helloworld.dodos
Traceback (most recent call last):
  File "C:\Users\conorob\Programming\dodos\dodos.py", line 5, in <module>
    from resource import setrlimit, RLIM_INFINITY, RLIMIT_STACK
ModuleNotFoundError: No module named 'resource'
```

**Comment by DennisMitchell** [comment]
Resource is required to keep complex programs (like the first quine I wrote) from segfaulting due to the increased recursion limit.

I didn't realize it was Unix only though. I'll put this part in a `try` block.
